# Generated by Django 5.0.6 on 2026-06-06 18:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0003_alter_shift_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('ILLNESS', 'Illness'), ('INJURY', 'Injury'), ('FAMILY_EMERGENCY', 'Family Emergency'), ('PERSONAL_EMERGENCY', 'Personal Emergency'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_incidents', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='shifts.shift')),
            ],
            options={
                'db_table': 'attendance_shift_incidents',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('CLOCKED_IN', 'Clocked In'), ('CLOCKED_OUT', 'Clocked Out'), ('EARLY_CHECKOUT_PENDING', 'Early Checkout Pending'), ('EARLY_CHECKOUT', 'Early Checkout'), ('NO_SHOW', 'No Show')], default='NOT_STARTED', max_length=30)),
                ('total_worked_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='shifts.shift')),
            ],
            options={
                'db_table': 'attendance_time_entries',
                'unique_together': {('employee', 'shift')},
            },
        ),
    ]
