# Generated by Django 5.0.6 on 2026-06-13 12:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('USERS', 'Users'), ('SHIFTS', 'Shifts'), ('SWAPS', 'Swaps'), ('ATTENDANCE', 'Attendance'), ('DEPARTMENTS', 'Departments'), ('AVAILABILITY', 'Availability'), ('NOTIFICATIONS', 'Notifications'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('INFO', 'Info')], default='INFO', max_length=20)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['category'], name='audit_logs_categor_27b551_idx'), models.Index(fields=['actor'], name='audit_logs_actor_i_0badd2_idx')],
            },
        ),
    ]
