# Generated by Django 5.0.6 on 2026-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('SCHEDULED', 'Scheduled'), ('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('CLOCKED_IN', 'Clocked In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOCKED_OUT', 'Clocked Out'), ('CANCELLED', 'Cancelled'), ('EARLY_CHECKOUT_PENDING', 'Early Checkout Pending'), ('EARLY_CHECKOUT', 'Early Checkout'), ('REPLACEMENT_REQUESTED', 'Replacement Requested'), ('COVERED', 'Covered')], default='OPEN', max_length=30),
        ),
    ]
