# Generated by Django 5.0.6 on 2026-06-05 16:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnoutScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('weekly_hours', models.FloatField(default=0)),
                ('consecutive_shifts', models.IntegerField(default=0)),
                ('night_shifts', models.IntegerField(default=0)),
                ('rest_hours', models.FloatField(default=8)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'burnout_scores',
                'ordering': ['-calculated_at'],
                'get_latest_by': 'calculated_at',
            },
        ),
    ]
